function output_struct = sdk_struct(struct_name)

arguments (Input)
    struct_name string {mustBeMember(struct_name, [...
        "tSdkRect", ...
        "tSdkCameraDevInfo", ...
        "tSdkResolutionRange", ...
        "tSdkImageResolution", ...
        "tSdkColorTemperatureDes", ...
        "tSdkFrameSpeed", "tSdkExpose", ...
        "tSdkTrigger", "tSdkPackLength", ...
        "tSdkPresetLut", ...
        "tSdkAeAlgorithm", ...
        "tSdkBayerDecodeAlgorithm", ...
        "tSdkFrameStatistic", ...
        "tSdkMediaType", ...
        "tGammaRange", ...
        "tContrastRange", ...
        "tRgbGainRange", ...
        "tSaturationRange", ...
        "tSharpnessRange", ...
        "tSdkIspCapacity", ...
        "tSdkCameraCapbility", ...
        "tSdkFrameHead", ...
        "sCameraFrame", ...
        "tSdkFrameEvent_", ...
        "tSdkGrabberStat" ...
    ])}
end

arguments (Output)
    output_struct struct
end

    switch struct_name
        case "tSdkRect"
            output_struct = struct( ...   
                'iLeft'   , int32(0), ...
                'iTop'    , int32(0), ... 
                'iWidth'  , int32(0), ... 
                'iHeight' , int32(0)  ...
            );

        case "tSdkCameraDevInfo"
            output_struct = struct( ...
                'acProductSeries' , int8(zeros(1, 32)), ... 
                'acProductName'   , int8(zeros(1, 32)), ... 
                'acFriendlyName'  , int8(zeros(1, 32)), ... 
                'acLinkName'      , int8(zeros(1, 32)), ... 
                'acDriverVersion' , int8(zeros(1, 32)), ...
                'acSensorType'    , int8(zeros(1, 32)), ...
                'acPortType'      , int8(zeros(1, 32)), ...
                'acSn'            , int8(zeros(1, 32)), ...
                'uInstance'       , uint32(0) ...
            );

        case "tSdkResolutionRange"
            output_struct = struct( ...
                'iHeightMax'          , uint32(0), ...
                'iHeightMin'          , uint32(0), ...
                'iWidthMax'           , uint32(0), ...
                'iWidthMin'           , uint32(0), ...
                'uSkipModeMask'       , uint32(0), ...
                'uBinSumModeMask'     , uint32(0), ...
                'uBinAverageModeMask' , uint32(0), ...
                'uResampleMask'       , uint32(0)  ...
            );

        case "tSdkImageResolution"
            output_struct = struct( ...
                'iIndex'          , uint32(0), ...
                'acDescription'   , int8(zeros(1, 32)), ...
                'uBinSumMode'     , uint32(0), ...
                'uBinAverageMode' , uint32(0), ...
                'uSkipMode'       , uint32(0), ...
                'uResampleMask'   , uint32(0), ...
                'iHOffsetFOV'     , uint32(0), ...
                'iVOffsetFOV'     , uint32(0), ...
                'iWidthFOV'       , uint32(0), ...
                'iHeightFOV'      , uint32(0), ...
                'iWidth'          , uint32(0), ...
                'iHeight'         , uint32(0), ...
                'iWidthZoomHd'    , uint32(0), ...
                'iHeightZoomHd'   , uint32(0), ...
                'iWidthZoomSw'    , uint32(0), ...
                'iHeightZoomSw'   , uint32(0)  ...
            );

        case "tSdkColorTemperatureDes"
            output_struct = struct( ...
                'iIndex'       , 'int32', ...
                'acDescription', int8(zeros(1, 32)) ...
            );

        case "tSdkFrameSpeed"
            output_struct = struct( ...
                );

        case "tSdkExpose"
            output_struct = struct( ...
                );

        case "tSdkTrigger"
            output_struct = struct( ...
                );

        case "tSdkPackLength"
            output_struct = struct( ...
                );

        case "tSdkPresetLut"
            output_struct = struct( ...
                );

        case "tSdkAeAlgorithm"
            output_struct = struct( ...
                );

        case "tSdkBayerDecodeAlgorithm"
            output_struct = struct( ...
                );

        case "tSdkFrameStatistic"
            output_struct = struct( ...
                );

        case "tSdkMediaType"
            output_struct = struct( ...
                );

        case "tGammaRange"
            output_struct = struct( ...
                );

        case "tContrastRange"
            output_struct = struct( ...
                );

        case "tRgbGainRange"
            output_struct = struct( ...
                );

        case "tSaturationRange"
            output_struct = struct( ...
                );

        case "tSharpnessRange"
            output_struct = struct( ...
                );

        case "tSdkIspCapacity"
            output_struct = struct( ...
                );

        case "tSdkCameraCapbility"
            output_struct = struct( ...
                );

        case "tSdkFrameHead"
            output_struct = struct( ...
                );

        case "sCameraFrame"
            output_struct = struct( ...
                );

        case "tSdkFrameEvent_"
            output_struct = struct( ...
                );

        case "tSdkGrabberStat"
            output_struct = struct( ...
                );


end


%%
structs.HWND__.members=struct('unused', 'int32');
structs.HDC__.members=struct('unused', 'int32');
structs.HBITMAP__.members=struct('unused', 'int32');

structs.tSdkRect.members=struct();
structs.tSdkCameraDevInfo.members=struct();
structs.tSdkResolutionRange.members=struct();
structs.tSdkImageResolution.members=struct();
structs.tSdkColorTemperatureDes.members=struct('iIndex', 'int32', 'acDescription', 'int8#32');
structs.tSdkFrameSpeed.members=struct('iIndex', 'int32', 'acDescription', 'int8#32');
structs.tSdkExpose.members=struct('uiTargetMin', 'uint32', 'uiTargetMax', 'uint32', 'uiAnalogGainMin', 'uint32', 'uiAnalogGainMax', 'uint32', 'fAnalogGainStep', 'single', 'uiExposeTimeMin', 'uint32', 'uiExposeTimeMax', 'uint32');
structs.tSdkTrigger.members=struct('iIndex', 'int32', 'acDescription', 'int8#32');
structs.tSdkPackLength.members=struct('iIndex', 'int32', 'acDescription', 'int8#32', 'iPackSize', 'uint32');
structs.tSdkPresetLut.members=struct('iIndex', 'int32', 'acDescription', 'int8#32');
structs.tSdkAeAlgorithm.members=struct('iIndex', 'int32', 'acDescription', 'int8#32');
structs.tSdkBayerDecodeAlgorithm.members=struct('iIndex', 'int32', 'acDescription', 'int8#32');
structs.tSdkFrameStatistic.members=struct('iTotal', 'int32', 'iCapture', 'int32', 'iLost', 'int32');
structs.tSdkMediaType.members=struct('iIndex', 'int32', 'acDescription', 'int8#32', 'iMediaType', 'uint32');
structs.tGammaRange.members=struct('iMin', 'int32', 'iMax', 'int32');
structs.tContrastRange.members=struct('iMin', 'int32', 'iMax', 'int32');
structs.tRgbGainRange.members=struct('iRGainMin', 'int32', 'iRGainMax', 'int32', 'iGGainMin', 'int32', 'iGGainMax', 'int32', 'iBGainMin', 'int32', 'iBGainMax', 'int32');
structs.tSaturationRange.members=struct('iMin', 'int32', 'iMax', 'int32');
structs.tSharpnessRange.members=struct('iMin', 'int32', 'iMax', 'int32');
structs.tSdkIspCapacity.members=struct('bMonoSensor', 'int32', 'bWbOnce', 'int32', 'bAutoWb', 'int32', 'bAutoExposure', 'int32', 'bManualExposure', 'int32', 'bAntiFlick', 'int32', 'bDeviceIsp', 'int32', 'bForceUseDeviceIsp', 'int32', 'bZoomHD', 'int32');
structs.tSdkCameraCapbility.members=struct('pTriggerDesc', 'tSdkTriggerPtr', 'iTriggerDesc', 'int32', 'pImageSizeDesc', 'tSdkImageResolutionPtr', 'iImageSizeDesc', 'int32', 'pClrTempDesc', 'tSdkColorTemperatureDesPtr', 'iClrTempDesc', 'int32', 'pMediaTypeDesc', 'tSdkMediaTypePtr', 'iMediaTypdeDesc', 'int32', 'pFrameSpeedDesc', 'tSdkFrameSpeedPtr', 'iFrameSpeedDesc', 'int32', 'pPackLenDesc', 'tSdkPackLengthPtr', 'iPackLenDesc', 'int32', 'iOutputIoCounts', 'int32', 'iInputIoCounts', 'int32', 'pPresetLutDesc', 'tSdkPresetLutPtr', 'iPresetLut', 'int32', 'iUserDataMaxLen', 'int32', 'bParamInDevice', 'int32', 'pAeAlmSwDesc', 'tSdkAeAlgorithmPtr', 'iAeAlmSwDesc', 'int32', 'pAeAlmHdDesc', 'tSdkAeAlgorithmPtr', 'iAeAlmHdDesc', 'int32', 'pBayerDecAlmSwDesc', 'tSdkBayerDecodeAlgorithmPtr', 'iBayerDecAlmSwDesc', 'int32', 'pBayerDecAlmHdDesc', 'tSdkBayerDecodeAlgorithmPtr', 'iBayerDecAlmHdDesc', 'int32', 'sExposeDesc', 'tSdkExpose', 'sResolutionRange', 'tSdkResolutionRange', 'sRgbGainRange', 'tRgbGainRange', 'sSaturationRange', 'tSaturationRange', 'sGammaRange', 'tGammaRange', 'sContrastRange', 'tContrastRange', 'sSharpnessRange', 'tSharpnessRange', 'sIspCapacity', 'tSdkIspCapacity');
structs.tSdkFrameHead.members=struct('uiMediaType', 'uint32', 'uBytes', 'uint32', 'iWidth', 'int32', 'iHeight', 'int32', 'iWidthZoomSw', 'int32', 'iHeightZoomSw', 'int32', 'bIsTrigger', 'int32', 'uiTimeStamp', 'uint32', 'uiExpTime', 'uint32', 'fAnalogGain', 'single', 'iGamma', 'int32', 'iContrast', 'int32', 'iSaturation', 'int32', 'fRgain', 'single', 'fGgain', 'single', 'fBgain', 'single');
structs.sCameraFrame.members=struct('head', 'tSdkFrameHead', 'pBuffer', 'uint8Ptr');
structs.tSdkFrameEvent_.members=struct('uType', 'uint32', 'uStatus', 'uint32', 'uFrameID', 'uint32', 'uWidth', 'uint32', 'uHeight', 'uint32', 'uPixelFormat', 'uint32', 'TimeStampL', 'uint32', 'TimeStampH', 'uint32');
structs.tSdkGrabberStat.members=struct('Width', 'int32', 'Height', 'int32', 'Disp', 'int32', 'Capture', 'int32', 'Lost', 'int32', 'Error', 'int32', 'DispFps', 'single', 'CapFps', 'single');