function c_struct = make_struct(struct_name)

arguments (Input)
    struct_name string {mustBeMember(struct_name, [...
        "tSdkRect", ...
        "tSdkCameraDevInfo", ...
        "tSdkResolutionRange", ...
        "tSdkImageResolution", ...
        "tSdkColorTemperatureDes", ...
        "tSdkFrameSpeed", ...
        "tSdkExpose", ...
        "tSdkTrigger", ...
        "tSdkPackLength", ...
        "tSdkPresetLut", ...
        "tSdkAeAlgorithm", ...
        "tSdkBayerDecodeAlgorithm", ...
        "tSdkFrameStatistic", ...
        "tSdkMediaType", ...
        "tGammaRange", ...
        "tContrastRange", ...
        "tRgbGainRange", ...
        "tSaturationRange", ...
        "tSharpnessRange", ...
        "tSdkIspCapacity", ...
        "tSdkCameraCapbility", ...
        "tSdkFrameHead", ...
        "sCameraFrame", ...
        "tSdkFrameEvent_", ...
        "tSdkGrabberStat" ...
    ])}
end

arguments (Output)
    c_struct
end

    mat_struct struct;

    switch struct_name
        case "tSdkRect"
            mat_struct = struct( ...
                'iLeft'   , int32(0), ...
                'iTop'    , int32(0), ...
                'iWidth'  , int32(0), ...
                'iHeight' , int32(0)  ...
            );

        case "tSdkCameraDevInfo"
            mat_struct = struct( ...
                'acProductSeries' , int8(zeros(1, 32)), ...
                'acProductName'   , int8(zeros(1, 32)), ...
                'acFriendlyName'  , int8(zeros(1, 32)), ...
                'acLinkName'      , int8(zeros(1, 32)), ...
                'acDriverVersion' , int8(zeros(1, 32)), ...
                'acSensorType'    , int8(zeros(1, 32)), ...
                'acPortType'      , int8(zeros(1, 32)), ...
                'acSn'            , int8(zeros(1, 32)), ...
                'uInstance'       , uint32(0) ...
            );

        case "tSdkResolutionRange"
            mat_struct = struct( ...
                'iHeightMax'          , int32(0),  ...
                'iHeightMin'          , int32(0),  ...
                'iWidthMax'           , int32(0),  ...
                'iWidthMin'           , int32(0),  ...
                'uSkipModeMask'       , uint32(0), ...
                'uBinSumModeMask'     , uint32(0), ...
                'uBinAverageModeMask' , uint32(0), ...
                'uResampleMask'       , uint32(0)  ...
            );

        case "tSdkImageResolution"
            mat_struct = struct( ...
                'iIndex'          , int32(0),           ...
                'acDescription'   , int8(zeros(1, 32)), ...
                'uBinSumMode'     , uint32(0),          ...
                'uBinAverageMode' , uint32(0),          ...
                'uSkipMode'       , uint32(0),          ...
                'uResampleMask'   , uint32(0),          ...
                'iHOffsetFOV'     , int32(0),           ...
                'iVOffsetFOV'     , int32(0),           ...
                'iWidthFOV'       , int32(0),           ...
                'iHeightFOV'      , int32(0),           ...
                'iWidth'          , int32(0),           ...
                'iHeight'         , int32(0),           ...
                'iWidthZoomHd'    , int32(0),           ...
                'iHeightZoomHd'   , int32(0),           ...
                'iWidthZoomSw'    , int32(0),           ...
                'iHeightZoomSw'   , int32(0)            ...
            );

        case "tSdkColorTemperatureDes"
            mat_struct = struct( ...
                'iIndex'        , int32(0),          ...
                'acDescription' , int8(zeros(1, 32)) ...
            );

        case "tSdkFrameSpeed"
            mat_struct = struct( ...
                'iIndex'        , int32(0),          ...
                'acDescription' , int8(zeros(1, 32)) ...
            );

        case "tSdkExpose"
            mat_struct = struct( ...
                'uiTargetMin'     , uint32(0), ...
                'uiTargetMax'     , uint32(0), ...
                'uiAnalogGainMin' , uint32(0), ...
                'uiAnalogGainMax' , uint32(0), ...
                'fAnalogGainStep' , single(0), ...
                'uiExposeTimeMin' , uint32(0), ...
                'uiExposeTimeMax' , uint32(0)  ...
            );

        case "tSdkTrigger"
            mat_struct = struct( ...
                'iIndex'        , int32(0),          ...
                'acDescription' , int8(zeros(1, 32)) ...
            );

        case "tSdkPackLength"
            mat_struct = struct( ...
                'iIndex'        , int32(0),           ...
                'acDescription' , int8(zeros(1, 32)), ...
                'iPackSize'     , uint32(0)           ...
            );

        case "tSdkPresetLut"
            mat_struct = struct( ...
                'iIndex'        , int32(0),           ...
                'acDescription' , int8(zeros(1, 32)), ...
            );

        case "tSdkAeAlgorithm"
            mat_struct = struct( ...
                'iIndex'        , int32(0),          ...
                'acDescription' , int8(zeros(1, 32)) ...
            );

        case "tSdkBayerDecodeAlgorithm"
            mat_struct = struct( ...
                'iIndex'        , int32(0),          ...
                'acDescription' , int8(zeros(1, 32)) ...
            );

        case "tSdkFrameStatistic"
            mat_struct = struct( ...
                'iTotal'   , int32(0), ...
                'iCapture' , int32(0), ...
                'iLost'    , int32(0)  ...
            );

        case "tSdkMediaType"
            mat_struct = struct( ...
                'iIndex'        , int32(0),           ...
                'acDescription' , int8(zeros(1, 32)), ...
                'iMediaType'    , uint32(0)           ...
            );

        case "tGammaRange"
            mat_struct = struct( ...
                'iMin' , int32(0),  ...
                'iMax' , int32(0)   ...
            );

        case "tContrastRange"
            mat_struct = struct( ...
                'iMin' , int32(0),  ...
                'iMax' , int32(0)   ...
            );

        case "tRgbGainRange"
            mat_struct = struct( ...
                'iRGainMin' , int32(0), ...
                'iRGainMax' , int32(0), ...
                'iGGainMin' , int32(0), ...
                'iGGainMax' , int32(0), ...
                'iBGainMin' , int32(0), ...
                'iBGainMax' , int32(0)  ...
            );

        case "tSaturationRange"
            mat_struct = struct( ...
                'iMin' , int32(0),  ...
                'iMax' , int32(0)   ...
            );

        case "tSharpnessRange"
            mat_struct = struct( ...
                'iMin' , int32(0),  ...
                'iMax' , int32(0)   ...
            );

        case "tSdkIspCapacity"
            mat_struct = struct( ...
                'bMonoSensor'        , int32(0), ...
                'bWbOnce'            , int32(0), ...
                'bAutoWb'            , int32(0), ...
                'bAutoExposure'      , int32(0), ...
                'bManualExposure'    , int32(0), ...
                'bAntiFlick'         , int32(0), ...
                'bDeviceIsp'         , int32(0), ...
                'bForceUseDeviceIsp' , int32(0), ...
                'bZoomHD'            , int32(0)  ...
            );

        case "tSdkCameraCapbility"
            temp_pTriggerDesc       = make_struct('tSdkTrigger');
            temp_pImageSizeDesc     = make_struct('tSdkImageResolution');
            temp_pClrTempDesc       = make_struct('tSdkColorTemperatureDes');
            temp_pMediaTypeDesc     = make_struct('tSdkMediaType');
            temp_pFrameSpeedDesc    = make_struct('tSdkFrameSpeed');
            temp_pPackLenDesc       = make_struct('tSdkPackLength');
            temp_pPresetLutDesc     = make_struct('tSdkPresetLut');
            temp_pAeAlmSwDesc       = make_struct('tSdkAeAlgorithm');
            temp_pAeAlmHdDesc       = make_struct('tSdkAeAlgorithm');
            temp_pBayerDecAlmSwDesc = make_struct('tSdkBayerDecodeAlgorithm');
            temp_pBayerDecAlmHdDesc = make_struct('tSdkBayerDecodeAlgorithm');

            mat_struct = struct( ...
                'pTriggerDesc'       , libpointer('tSdkTrigger', temp_pTriggerDesc),                     ...  % 'tSdkTriggerPtr', ...
                'iTriggerDesc'       , int32(0), ...
                'pImageSizeDesc'     , libpointer('tSdkImageResolution', temp_pImageSizeDesc),           ...  % 'tSdkImageResolutionPtr', ...
                'iImageSizeDesc'     , int32(0), ...
                'pClrTempDesc'       , libpointer('tSdkColorTemperatureDes', temp_pClrTempDesc),         ...  % 'tSdkColorTemperatureDesPtr', ...
                'iClrTempDesc'       , int32(0), ...
                'pMediaTypeDesc'     , libpointer('tSdkMediaType', temp_pMediaTypeDesc),                 ...  % 'tSdkMediaTypePtr', ...
                'iMediaTypdeDesc'    , int32(0), ...
                'pFrameSpeedDesc'    , libpointer('tSdkFrameSpeed', temp_pFrameSpeedDesc),               ...  % 'tSdkFrameSpeedPtr', ...
                'iFrameSpeedDesc'    , int32(0), ...
                'pPackLenDesc'       , libpointer('tSdkPackLength', temp_pPackLenDesc),                  ...  % 'tSdkPackLengthPtr', ...
                'iPackLenDesc'       , int32(0), ...
                'iOutputIoCounts'    , int32(0), ...
                'iInputIoCounts'     , int32(0), ...
                'pPresetLutDesc'     , libpointer('tSdkPresetLut', temp_pPresetLutDesc),                  ...  % 'tSdkPresetLutPtr', ...
                'iPresetLut'         , int32(0), ...
                'iUserDataMaxLen'    , int32(0), ...
                'bParamInDevice'     , int32(0), ...
                'pAeAlmSwDesc'       , libpointer('tSdkAeAlgorithm', temp_pAeAlmSwDesc),                  ...  % 'tSdkAeAlgorithmPtr', ...
                'iAeAlmSwDesc'       , int32(0), ...
                'pAeAlmHdDesc'       , libpointer('tSdkAeAlgorithm', temp_pAeAlmHdDesc),                  ...  % 'tSdkAeAlgorithmPtr', ...
                'iAeAlmHdDesc'       , int32(0), ...
                'pBayerDecAlmSwDesc' , libpointer('tSdkBayerDecodeAlgorithm', temp_pBayerDecAlmSwDesc),   ...  % 'tSdkBayerDecodeAlgorithmPtr', ...
                'iBayerDecAlmSwDesc' , int32(0), ...
                'pBayerDecAlmHdDesc' , libpointer('tSdkBayerDecodeAlgorithm', temp_pBayerDecAlmHdDesc), ...  % 'tSdkBayerDecodeAlgorithmPtr', ...
                'iBayerDecAlmHdDesc' , int32(0), ...
                'sExposeDesc'        , make_struct("tSdkExpose"),           ...  % 'tSdkExpose',           ...
                'sResolutionRange'   , make_struct("tSdkResolutionRange"),  ...  % 'tSdkResolutionRange',  ...
                'sRgbGainRange'      , make_struct("tRgbGainRange"),        ...  % 'tRgbGainRange',        ...
                'sSaturationRange'   , make_struct("tSaturationRange"),     ...  % 'tSaturationRange',     ...
                'sGammaRange'        , make_struct("tGammaRange"),          ...  % 'tGammaRange',          ...
                'sContrastRange'     , make_struct("tContrastRange"),       ...  % 'tContrastRange',       ...
                'sSharpnessRange'    , make_struct("tSharpnessRange"),      ...  % 'tSharpnessRange',      ...
                'sIspCapacity'       , make_struct("tSdkIspCapacity")       ...  % 'tSdkIspCapacity'       ...
            );

        case "tSdkFrameHead"
            mat_struct = struct( ...
                'uiMediaType'   , uint32(0), ...
                'uBytes'        , uint32(0), ...
                'iWidth'        , int32(0),  ...
                'iHeight'       , int32(0),  ...
                'iWidthZoomSw'  , int32(0),  ...
                'iHeightZoomSw' , int32(0),  ...
                'bIsTrigger'    , int32(0),  ...
                'uiTimeStamp'   , uint32(0), ...
                'uiExpTime'     , uint32(0), ...
                'fAnalogGain'   , single(0), ...
                'iGamma'        , int32(0),  ...
                'iContrast'     , int32(0),  ...
                'iSaturation'   , int32(0),  ...
                'fRgain'        , single(0), ...
                'fGgain'        , single(0), ...
                'fBgain'        , single(0)  ...
            );

        case "sCameraFrame"
            mat_struct = struct( ...
                'head'    , 'tSdkFrameHead', ...
                'pBuffer' , 'uint8Ptr'       ...
            );

        case "tSdkFrameEvent_"
            mat_struct = struct( ...
                'uType'        , uint32(0), ...
                'uStatus'      , uint32(0), ...
                'uFrameID'     , uint32(0), ...
                'uWidth'       , uint32(0), ...
                'uHeight'      , uint32(0), ...
                'uPixelFormat' , uint32(0), ...
                'TimeStampL'   , uint32(0), ...
                'TimeStampH'   , uint32(0)  ...
            );

        case "tSdkGrabberStat"
            mat_struct = struct( ...
                'Width'   , int32(0),  ...
                'Height'  , int32(0),  ...
                'Disp'    , int32(0),  ...
                'Capture' , int32(0),  ...
                'Lost'    , int32(0),  ...
                'Error'   , int32(0),  ...
                'DispFps' , single(0), ...
                'CapFps'  , single(0)  ...
            );

        otherwise
            error('Invalid structure type');
    end

    c_struct = libstruct(struct_name, mat_struct);

    clear(temp_pTriggerDesc);
    clear(temp_pImageSizeDesc);
    clear(temp_pClrTempDesc);
    clear(temp_pMediaTypeDesc);
    clear(temp_pFrameSpeedDesc);
    clear(temp_pPackLenDesc);
    clear(temp_pPresetLutDesc);
    clear(temp_pAeAlmSwDesc);
    clear(temp_pAeAlmHdDesc);
    clear(temp_pBayerDecAlmSwDesc);
    clear(temp_pBayerDecAlmHdDesc);

    clear(mat_struct);
end


%%
structs.HWND__.members=struct('unused', int32(0));
structs.HDC__.members=struct('unused', int32(0));
structs.HBITMAP__.members=struct('unused', int32(0));
